name: Build images
on:
  release:
    types:
      - published

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      release_number: ${{ steps.validate_release_name.outputs.RELEASE_NUMBER }}
    steps:
      - name: get version
        id: extract_version
        run: |
          echo "${{ github.event.release.name }}"
          echo "${{ github.event.release.body }}"
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.event.release.tag_name }}" | sed -n 's/^v\([^ ]*\)/\1/p'
          echo "version=$(echo "${{ github.event.release.tag_name }}" | sed -n 's/^v\([^ ]*\)/\1/p')" >> $GITHUB_ENV
      - name: get ticket name
        id: ticket_name
        run: |
          echo "${{ github.event.release.body }}" | grep -o -i "updates from bc-[0-9]\+" | head -n 1 | grep -o -i "bc-[0-9]\+" | tr '[:lower:]' '[:upper:]'
          echo "ticket_name=$(echo "${{ github.event.release.body }}" | grep -o -i "updates from bc-[0-9]\+" | head -n 1 | grep -o -i "bc-[0-9]\+" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
      - name: Validate release name
        id: validate_release_name
        run: |
          if [ "$(echo "${{ github.event.release.name }}" | grep -c 'Pre-release 20')" -eq 1 ]; then 
            echo "Release name is valid, creating a tenant (${{ github.event.release.name }})"
            echo "Release number ($(echo "${{ github.event.release.name }}" | sed -n 's/.* \([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\) .*/\1/p'))"
            echo "RELEASE_NUMBER=$(echo "${{ github.event.release.name }}" | sed -n 's/.* \([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\) .*/\1/p')" >> "$GITHUB_OUTPUT"
          else
            echo "Release name is invalid (${{ github.event.release.name}})"
          fi

  create-tenant-staging-instance:
    needs:
      - build-image
    runs-on: ubuntu-latest
    env:
      TENANT_NAME: "stage-${{ needs.build-image.outputs.release_number }}"
    steps:
      - name: Print tenant name
        run: |
          echo "Tenant name: $TENANT_NAME"
