name: Build images
on:
  release:
    types:
      - published

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        id: extract_version
        run: |
          echo "${{ github.event.release.name }}"
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.event.release.tag_name }}" | sed -n 's/^v\([^ ]*\)/\1/p'
          echo "version=$(echo "${{ github.event.release.tag_name }}" | sed -n 's/^v\([^ ]*\)/\1/p')" >> $GITHUB_ENV
      - name: Validate release name
        id: validate_release_name
        run: |
          if [ "$(echo "${{ github.event.release.name }}" | grep -c 'Pre-release 20')" -eq 1 ]; then 
            echo "Release name is valid, creating a tenant (${{ github.event.release.name }})"
            echo "Release number ($(echo "${{ github.event.release.name }}" | sed 's/Pre-release //'))"
            echo "RELEASE_NUMBER=$(echo "${{ github.event.release.name }}" | sed 's/Pre-release //')" >> "$GITHUB_OUTPUT"
          else
            echo "Release name is invalid (${{ github.event.release.name}})"
          fi
