name: Create a pre-release
on:
  push:
    branches:
      - main

jobs:
  create-pre-release:
    if: ${{ startsWith(github.event.head_commit.message, 'release v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract version
        id: extract_version
        run: |
          echo "version=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/^release \([^ ]*\)/\1/p')" >> $GITHUB_OUTPUT
      - name: Echo extracted version
        run: |
          echo "${{ steps.extract_version.outputs.version }}"
          echo "${{ github.event.head_commit.message }}"
      - name: Get current year
        id: current_year
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY"
      - uses: actions/download-artifact@v4
        with:
          name: pre_release_iteration_number
      - name: Read artifact release number
        run: |
          cat pre_release_iteration_number.txt
      - name: Outputs release name
        if: always()
        run: |
          echo "Pre-release ${{ steps.current_year.outputs.year }}.${{ steps.current_year.outputs.month }} (${{ steps.extract_version.outputs.version }})"
          echo "Run number (${{ github.run_number }})"
          echo "Pre-release ${{ steps.current_year.outputs.year }}.${{ steps.current_year.outputs.month }} (${{ steps.extract_version.outputs.version }})" > pre_release_iteration_number.txt
      - name: Upload iteration artifact
        uses: actions/upload-artifact@v4
        with:
          name: pre_release_iteration_number
          path: pre_release_iteration_number.txt
      - name: Create a pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Pre-release ${{ steps.extract_version.outputs.version }}
          body: |
            Auto generated pre-release for ${{ steps.extract_version.outputs.version }}.
          prerelease: true
          draft: false
