name: Create a pre-release
on:
  push:
    branches:
      - main

jobs:
  create-pre-release:
    if: ${{ startsWith(github.event.head_commit.message, 'release v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract version
        id: extract_version
        run: |
          echo "version=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/^release \([^ ]*\)/\1/p')" >> $GITHUB_OUTPUT
      - name: Echo extracted version
        run: |
          echo "${{ steps.extract_version.outputs.version }}"
          echo "${{ github.event.head_commit.message }}"
      - name: Get current year
        id: current_year
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY"
      - name: Download iteration artifact
        run: |
          aws s3 cp s3://pre-release-number/pre-release-number.json ./pre-release-number.json
          cat ./pre-release-number.json
      - name: Outputs release name
        if: always()
        run: |
          echo "Pre-release ${{ steps.current_year.outputs.year }}.${{ steps.current_year.outputs.month }} (${{ steps.extract_version.outputs.version }})"
          echo "Run number (${{ github.run_number }})"
          echo "Pre-release ${{ steps.current_year.outputs.year }}.${{ steps.current_year.outputs.month }} (${{ steps.extract_version.outputs.version }})" > pre_release_iteration_number.txt
      - name: Upload iteration artifact
        run: |
          aws s3 cp ./pre-release-number.json s3://pre-release-number/pre-release-number.json
      - name: Create a pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Pre-release ${{ steps.extract_version.outputs.version }}
          body: |
            Auto generated pre-release for ${{ steps.extract_version.outputs.version }}.
          prerelease: true
          draft: false
