name: Create a pre-release
on:
  push:
    branches:
      - main

jobs:
  create-pre-release:
    if: ${{ startsWith(github.event.head_commit.message, 'release v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract version
        id: extract_version
        run: |
          echo "version=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/^release \([^ ]*\)/\1/p')" >> $GITHUB_OUTPUT
      - name: Echo extracted version
        run: |
          echo "${{ steps.extract_version.outputs.version }}"
          echo "${{ github.event.head_commit.message }}"
      - name: Get current year
        id: current_year
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY"
      - name: Get current month
        id: current_month
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        with:
          format: "MM"
      - name: Outputs
        run: |
          echo "The time was ${{ steps.current_year.outputs.time }}"
          echo "The year was ${{ steps.current_year.outputs.year }}"
          echo "The month was ${{ steps.current_year.outputs.month }}"
          echo "The day was ${{ steps.current_year.outputs.day }}"
          echo "The hours was ${{ steps.current_year.outputs.hours }}"
          echo "The minutes was ${{ steps.current_year.outputs.minutes }}"
          echo "The seconds was ${{ steps.current_year.outputs.seconds }}"
          echo "The milliseconds was ${{ steps.current_year.outputs.milliseconds }}"
          echo "The day_of_week was ${{ steps.current_year.outputs.day_of_week }}"
          echo "The week_of_year was ${{ steps.current_year.outputs.week_of_year }}"
          echo "The milliseconds_since_epoch was ${{ steps.current_year.outputs.milliseconds_since_epoch }}"
      - name: Create a pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Pre-release ${{ steps.extract_version.outputs.version }}
          body: |
            Auto generated pre-release for ${{ steps.extract_version.outputs.version }}.
          prerelease: true
          draft: false
